version: '3.8'

services:
  web:
    image: djangoondocker
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
      - 3000:3000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
#      PGADMIN_DEFAULT_PASSWORD: "admin"
#    ports:
#      - "4007:80"
#    depends_on:
#        - db


  

volumes:
  postgres_data:
